apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-aks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-aks
  template:
    metadata:
      labels:
        app: hello-aks
    spec:
      containers:
      - name: web-server
        image: nginx:latest # Using a public image so you don't have to push to ACR yet
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-aks-service
spec:
  type: LoadBalancer # This gives you a Public IP in Azure
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: hello-aks
